# Generated by Django 2.2.17 on 2020-11-12 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201112_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='hgfhgfh',
            new_name='dgyryrturut',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='jhgfhjgfjh',
            new_name='drgyeryeyrthyfh',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='jjghjghgfhfhgf',
            new_name='fgdfg',
        ),
        migrations.AddField(
            model_name='customtext',
            name='ghjfhfhdgdgdg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
