# Generated by Django 2.2.17 on 2020-11-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="cgvfbgbhnjnmj",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
