# Generated by Django 2.2.17 on 2020-11-12 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_test_cgvfbgbhnjnmj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtext',
            old_name='drgyeryeyrthyfh',
            new_name='ghfhgfhfhfhfhggfhf35435354353',
        ),
        migrations.RenameField(
            model_name='customtext',
            old_name='ghjfhfhdgdgdg',
            new_name='jhg',
        ),
    ]
